"""Ollama-backed recipe generation for the local backend."""

from __future__ import annotations

from dataclasses import dataclass, field
import hashlib
import json
import logging
import re
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from .config import OllamaConfig
from .contracts import RecipeRecord, SuggestRequest

LOGGER = logging.getLogger("kidschef.ollama")

SUPERVISED_APPLIANCES = {
    "blender",
    "food_processor",
    "hand_mixer",
    "stand_mixer",
}


@dataclass(frozen=True, slots=True)
class OllamaRecipeGenerationResult:
    status: str
    recipes: tuple[RecipeRecord, ...] = ()
    reasons_by_recipe_id: dict[str, str] = field(default_factory=dict)
    note: str | None = None
    provider: str = "ollama"
    model: str | None = None
    host: str | None = None

    @property
    def used(self) -> bool:
        return self.status == "ok" and bool(self.recipes)

    @property
    def ranked_recipe_ids(self) -> tuple[str, ...]:
        return tuple(
            recipe["recipe_id"]
            for recipe in self.recipes
            if isinstance(recipe.get("recipe_id"), str)
        )

    def as_payload(self) -> dict[str, Any]:
        return {
            "status": self.status,
            "provider": self.provider,
            "model": self.model,
            "host": self.host,
            "used": self.used,
            "ranked_recipe_ids": list(self.ranked_recipe_ids),
            "reasons_by_recipe_id": dict(self.reasons_by_recipe_id),
            "note": self.note,
        }


class OllamaRecipeGenerator:
    """Generate compact recipe suggestions and expand them on demand."""

    def __init__(self, config: OllamaConfig | None = None) -> None:
        self._config = config or OllamaConfig.from_env()

    @property
    def config(self) -> OllamaConfig:
        return self._config

    def generate(self, request: SuggestRequest) -> OllamaRecipeGenerationResult:
        if not self._config.is_enabled:
            return OllamaRecipeGenerationResult(status="disabled", note="Ollama is disabled in configuration.")

        payload = self._build_recommendation_payload(request)
        try:
            response = self._call_ollama(payload)
        except (OSError, HTTPError, URLError, TimeoutError, ValueError, json.JSONDecodeError) as exc:
            return OllamaRecipeGenerationResult(
                status="unavailable",
                note=f"Ollama generation unavailable: {exc.__class__.__name__}",
                model=self._config.model,
                host=self._config.host,
            )

        recipes = self._extract_summary_recipes(response, request)
        if not recipes:
            return OllamaRecipeGenerationResult(
                status="unavailable",
                note="Ollama response did not contain usable recipes.",
                model=self._config.model,
                host=self._config.host,
            )

        reasons = self._extract_reasons(response, recipes)
        return OllamaRecipeGenerationResult(
            status="ok",
            recipes=tuple(recipes),
            reasons_by_recipe_id=reasons,
            note="Generated by Ollama.",
            model=self._config.model,
            host=self._config.host,
        )

    def expand_recipe(self, summary_recipe: RecipeRecord) -> RecipeRecord | None:
        if not self._config.is_enabled:
            return None
        payload = self._build_expand_payload(summary_recipe)
        try:
            response = self._call_ollama(payload)
        except (OSError, HTTPError, URLError, TimeoutError, ValueError, json.JSONDecodeError):
            return None
        return _normalize_expanded_recipe(response.get("recipe"), summary_recipe)

    def _build_recommendation_payload(self, request: SuggestRequest) -> dict[str, Any]:
        limit = max(1, min(request.limit, min(self._config.max_candidates, 3)))
        return {
            "model": self._config.model,
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "You generate compact recipe recommendations for a kid-focused cooking app. "
                        "Generate short recipe summaries only, already ordered from best to worst. "
                        "Do not use the pantry ingredients list to choose the recipes. "
                        "Choose recipes based on the requested meal, child-friendliness, safety rules, household filters, and how teachable the steps are. "
                        "Keep the output short so a local model can answer quickly. "
                        "Respect appliance and diet limits. "
                        "Recipes that use blenders, food processors, hand mixers, or stand mixers must require adult supervision. "
                        "Return JSON only with keys recipes and reasons_by_index. "
                        "Each recipe must include only: title, summary, meal_type, ingredient_names, prep_time_minutes, cook_time_minutes, difficulty, skill_level, appliances, allergens, diet_tags, safety_flags, adult_help_required."
                    ),
                },
                {
                    "role": "user",
                    "content": json.dumps(
                        {
                            "meal_type": request.meal_type,
                            "allergens": request.allergens,
                            "diet_tags": request.diet_tags,
                            "appliances": request.appliances,
                            "safety_mode": request.safety_mode,
                            "limit": limit,
                        },
                        ensure_ascii=True,
                    ),
                },
            ],
            "stream": False,
            "format": "json",
            "options": {"temperature": 0},
        }

    def _build_expand_payload(self, recipe: RecipeRecord) -> dict[str, Any]:
        ingredient_names = [
            item.get("name")
            for item in recipe.get("ingredients", [])
            if isinstance(item, dict) and isinstance(item.get("name"), str)
        ]
        appliance_names = [
            item.get("name") if isinstance(item, dict) else item
            for item in recipe.get("appliances", [])
        ]
        return {
            "model": self._config.model,
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "Expand a compact KidsChef recipe summary into one complete structured recipe. "
                        "Keep steps concrete, short, and age-appropriate. "
                        "Recipes using blenders, food processors, hand mixers, or stand mixers must require adult supervision. "
                        "Return JSON only with key recipe. "
                        "The recipe must include: ingredients, steps, servings, prep_time_minutes, cook_time_minutes, difficulty, skill_level, appliances, allergens, diet_tags, safety_flags, adult_help_required."
                    ),
                },
                {
                    "role": "user",
                    "content": json.dumps(
                        {
                            "recipe_id": recipe.get("recipe_id"),
                            "title": recipe.get("title"),
                            "summary": recipe.get("summary"),
                            "meal_type": recipe.get("meal_type"),
                            "ingredient_names": ingredient_names,
                            "appliances": appliance_names,
                            "adult_help_required": recipe.get("adult_help_required"),
                            "safety_flags": recipe.get("safety_flags", []),
                        },
                        ensure_ascii=True,
                    ),
                },
            ],
            "stream": False,
            "format": "json",
            "options": {"temperature": 0},
        }

    def _call_ollama(self, payload: dict[str, Any]) -> dict[str, Any]:
        body = json.dumps(payload).encode("utf-8")
        LOGGER.info("ollama.request %s", json.dumps(payload, ensure_ascii=True))
        request = Request(
            self._config.host.rstrip("/") + "/api/chat",
            data=body,
            method="POST",
            headers={"Content-Type": "application/json; charset=utf-8"},
        )
        with urlopen(request, timeout=self._config.timeout_seconds) as response:
            raw = response.read().decode("utf-8")
        LOGGER.info("ollama.response.raw %s", raw)
        parsed = json.loads(raw)
        if not isinstance(parsed, dict):
            raise ValueError("unexpected Ollama response")
        message = parsed.get("message")
        if isinstance(message, dict) and isinstance(message.get("content"), str):
            content = message["content"]
        elif isinstance(parsed.get("response"), str):
            content = parsed["response"]
        else:
            raise ValueError("missing Ollama content")
        content = content.strip()
        if not content:
            raise ValueError("empty Ollama content")
        LOGGER.info("ollama.response.content %s", content)
        parsed_content = json.loads(content)
        if not isinstance(parsed_content, dict):
            raise ValueError("invalid Ollama JSON content")
        LOGGER.info("ollama.response.parsed %s", json.dumps(parsed_content, ensure_ascii=True))
        return parsed_content

    def _extract_summary_recipes(self, response: dict[str, Any], request: SuggestRequest) -> list[RecipeRecord]:
        payload = response.get("recipes")
        if not isinstance(payload, list):
            return []
        recipes: list[RecipeRecord] = []
        for index, item in enumerate(payload[: request.limit], start=1):
            normalized = _normalize_summary_recipe(item, index=index, request=request)
            if normalized is not None:
                recipes.append(normalized)
        return recipes

    def _extract_reasons(
        self,
        response: dict[str, Any],
        recipes: list[RecipeRecord],
    ) -> dict[str, str]:
        reason_payload = response.get("reasons_by_index")
        if not isinstance(reason_payload, dict):
            return {}
        result: dict[str, str] = {}
        for index, recipe in enumerate(recipes, start=1):
            recipe_id = recipe.get("recipe_id")
            if not isinstance(recipe_id, str):
                continue
            reason = reason_payload.get(str(index))
            if isinstance(reason, str) and reason.strip():
                result[recipe_id] = reason.strip()
            elif isinstance(reason, list):
                parts = [item.strip() for item in reason if isinstance(item, str) and item.strip()]
                if parts:
                    result[recipe_id] = " ".join(parts)
        return result


def annotate_ai_assistance(
    recipes: list[dict[str, Any]],
    generation: OllamaRecipeGenerationResult,
) -> list[dict[str, Any]]:
    if generation.status != "ok":
        return recipes

    reason_map = generation.reasons_by_recipe_id
    order_map = {recipe_id: index for index, recipe_id in enumerate(generation.ranked_recipe_ids)}

    annotated: list[dict[str, Any]] = []
    for recipe in recipes:
        enriched = dict(recipe)
        recipe_id = enriched.get("recipe_id")
        if isinstance(recipe_id, str):
            enriched["ai_rank"] = order_map.get(recipe_id)
            if recipe_id in reason_map:
                enriched["ai_reason"] = reason_map[recipe_id]
        annotated.append(enriched)
    return annotated


def _normalize_summary_recipe(
    payload: Any,
    *,
    index: int,
    request: SuggestRequest,
) -> RecipeRecord | None:
    if not isinstance(payload, dict):
        return None

    title = _clean_string(payload.get("title"))
    summary = _clean_string(payload.get("summary"))
    meal_type = _clean_string(payload.get("meal_type")) or request.meal_type or "snack"
    ingredient_names = payload.get("ingredient_names")
    if not title or not summary or not isinstance(ingredient_names, list):
        return None

    ingredients = [
        {
            "name": name,
            "amount": None,
            "unit": None,
            "preparation": None,
            "optional": False,
            "allergen_tags": [],
        }
        for raw in ingredient_names
        if (name := _clean_string(raw))
    ]
    if not ingredients:
        return None

    slug_source = f"{meal_type}:{title}:{index}"
    digest = hashlib.sha1(slug_source.encode("utf-8")).hexdigest()[:10]
    recipe_id = f"llama-{_slugify(meal_type)}-{_slugify(title)}-{digest}"
    appliance_names = _clean_string_list(payload.get("appliances"))
    adult_help_required, safety_flags = _supervision_flags(
        appliance_names,
        bool(payload.get("adult_help_required", False)),
        _clean_string_list(payload.get("safety_flags")),
        [],
    )

    return {
        "recipe_id": recipe_id,
        "title": title,
        "meal_type": meal_type,
        "summary": summary,
        "ingredients": ingredients,
        "steps": [],
        "servings": _coerce_int(payload.get("servings"), default=1),
        "prep_time_minutes": _coerce_int(payload.get("prep_time_minutes"), default=5),
        "cook_time_minutes": _coerce_int(payload.get("cook_time_minutes"), default=0),
        "difficulty": _clean_string(payload.get("difficulty")) or "easy",
        "skill_level": _clean_string(payload.get("skill_level")) or "guided_beginner",
        "appliances": [{"name": name, "required": True} for name in appliance_names],
        "allergens": _clean_string_list(payload.get("allergens")),
        "diet_tags": _clean_string_list(payload.get("diet_tags")),
        "safety_flags": safety_flags,
        "adult_help_required": adult_help_required,
        "source": "ollama_generated",
        "validation_status": "validated",
        "tags": [],
        "summary_only": True,
    }


def _normalize_expanded_recipe(payload: Any, summary_recipe: RecipeRecord) -> RecipeRecord | None:
    if not isinstance(payload, dict):
        return None
    ingredients_payload = payload.get("ingredients")
    steps_payload = payload.get("steps")
    if not isinstance(ingredients_payload, list) or not isinstance(steps_payload, list):
        return None

    ingredients: list[dict[str, Any]] = []
    for item in ingredients_payload:
        if not isinstance(item, dict):
            continue
        name = _clean_string(item.get("name"))
        if not name:
            continue
        ingredients.append(
            {
                "name": name,
                "amount": item.get("amount"),
                "unit": _clean_string(item.get("unit")),
                "preparation": _clean_string(item.get("preparation")),
                "optional": bool(item.get("optional", False)),
                "allergen_tags": _clean_string_list(item.get("allergen_tags")),
            }
        )
    if not ingredients:
        return None

    steps: list[dict[str, Any]] = []
    for fallback_order, item in enumerate(steps_payload, start=1):
        if not isinstance(item, dict):
            continue
        instruction = _clean_string(item.get("instruction"))
        if not instruction:
            continue
        requires_appliance = _clean_string_list(item.get("requires_appliance"))
        timers = []
        for timer in item.get("timers", []):
            if not isinstance(timer, dict):
                continue
            label = _clean_string(timer.get("label"))
            duration = _coerce_int(timer.get("duration_seconds"), default=0)
            if not label or duration <= 0:
                continue
            timers.append(
                {
                    "label": label,
                    "duration_seconds": duration,
                    "start_condition": _clean_string(timer.get("start_condition")),
                }
            )
        step_requires_help = bool(item.get("requires_adult_help", False)) or bool(SUPERVISED_APPLIANCES.intersection(requires_appliance))
        safety_level = _clean_string(item.get("safety_level")) or "safe"
        if step_requires_help and safety_level == "safe":
            safety_level = "adult_help"
        steps.append(
            {
                "step_id": _clean_string(item.get("step_id")) or f"step-{fallback_order}",
                "order": _coerce_int(item.get("order"), default=fallback_order),
                "instruction": instruction,
                "safety_level": safety_level,
                "requires_adult_help": step_requires_help,
                "requires_appliance": requires_appliance,
                "timers": timers,
                "ingredient_refs": _clean_string_list(item.get("ingredient_refs")),
                "warnings": _clean_string_list(item.get("warnings")),
            }
        )
    if not steps:
        return None

    appliance_names = _clean_string_list(payload.get("appliances"))
    adult_help_required, safety_flags = _supervision_flags(
        appliance_names,
        bool(payload.get("adult_help_required", False)),
        _clean_string_list(payload.get("safety_flags")) + list(summary_recipe.get("safety_flags", [])),
        steps,
    )
    allergens = sorted(
        set(_clean_string_list(payload.get("allergens")))
        | {
            tag
            for ingredient in ingredients
            for tag in ingredient["allergen_tags"]
            if isinstance(tag, str) and tag
        }
    )

    enriched = dict(summary_recipe)
    enriched.update(
        {
            "ingredients": ingredients,
            "steps": steps,
            "servings": _coerce_int(payload.get("servings"), default=summary_recipe.get("servings", 1)),
            "prep_time_minutes": _coerce_int(payload.get("prep_time_minutes"), default=summary_recipe.get("prep_time_minutes", 5)),
            "cook_time_minutes": _coerce_int(payload.get("cook_time_minutes"), default=summary_recipe.get("cook_time_minutes", 0)),
            "difficulty": _clean_string(payload.get("difficulty")) or summary_recipe.get("difficulty", "easy"),
            "skill_level": _clean_string(payload.get("skill_level")) or summary_recipe.get("skill_level", "guided_beginner"),
            "appliances": [{"name": name, "required": True} for name in appliance_names] or summary_recipe.get("appliances", []),
            "allergens": allergens,
            "diet_tags": _clean_string_list(payload.get("diet_tags")) or summary_recipe.get("diet_tags", []),
            "safety_flags": safety_flags,
            "adult_help_required": adult_help_required,
            "summary_only": False,
        }
    )
    return enriched


def _supervision_flags(
    appliance_names: list[str],
    adult_help_required: bool,
    safety_flags: list[str],
    steps: list[dict[str, Any]],
) -> tuple[bool, list[str]]:
    step_requires_help = any(bool(step.get("requires_adult_help")) for step in steps)
    supervised_appliance_used = bool(SUPERVISED_APPLIANCES.intersection(appliance_names))
    result_help = adult_help_required or step_requires_help or supervised_appliance_used
    result_flags = set(safety_flags)
    if result_help:
        result_flags.add("adult_help")
    for appliance_name in sorted(SUPERVISED_APPLIANCES.intersection(appliance_names)):
        result_flags.add(appliance_name)
    return result_help, sorted(result_flags)


def _clean_string(value: Any) -> str | None:
    if not isinstance(value, str):
        return None
    cleaned = value.strip()
    return cleaned or None


def _clean_string_list(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    result: list[str] = []
    for item in value:
        if isinstance(item, str):
            cleaned = item.strip().lower()
            if cleaned:
                result.append(cleaned)
    return result


def _coerce_int(value: Any, *, default: int) -> int:
    if isinstance(value, bool):
        return default
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return int(value)
    return default


def _slugify(value: str) -> str:
    cleaned = re.sub(r"[^a-z0-9]+", "-", value.strip().lower())
    cleaned = cleaned.strip("-")
    return cleaned or "recipe"
