from __future__ import annotations

from .recipe_models import ApplianceRequirement, Ingredient, Recipe, Step, Timer


SEED_RECIPES: tuple[Recipe, ...] = (
    Recipe(
        recipe_id="breakfast-berry-yogurt-parfait",
        title="Berry Yogurt Parfait",
        meal_type="breakfast",
        summary="A calm no-cook breakfast with yogurt, berries, and granola.",
        ingredients=(
            Ingredient("plain yogurt", amount="1 cup", allergen_tags=("dairy",)),
            Ingredient("berries", amount="1/2 cup"),
            Ingredient("granola", amount="1/3 cup", allergen_tags=("wheat",)),
        ),
        steps=(
            Step("step-1", 1, "Spoon the yogurt into a bowl."),
            Step("step-2", 2, "Add the berries on top."),
            Step("step-3", 3, "Sprinkle granola over the bowl and eat."),
        ),
        servings=1,
        prep_time_minutes=5,
        cook_time_minutes=0,
        difficulty="easy",
        skill_level="independent_beginner",
        appliances=(),
        allergens=("dairy", "wheat"),
        diet_tags=("vegetarian",),
        safety_flags=(),
        adult_help_required=False,
        source="curated",
        validation_status="validated",
    ),
    Recipe(
        recipe_id="breakfast-microwave-egg-mug",
        title="Microwave Egg Mug",
        meal_type="breakfast",
        summary="A quick egg breakfast that needs an adult for the hot step.",
        ingredients=(
            Ingredient("egg", amount=1, allergen_tags=("egg",)),
            Ingredient("milk", amount="2 tbsp", allergen_tags=("dairy",)),
            Ingredient("cheddar cheese", amount="2 tbsp", allergen_tags=("dairy",)),
        ),
        steps=(
            Step("step-1", 1, "Crack the egg into a microwave-safe mug.", safety_level="adult_help", requires_adult_help=True),
            Step(
                "step-2",
                2,
                "Ask an adult to microwave the mug for 60 seconds.",
                safety_level="adult_help",
                requires_adult_help=True,
                requires_appliance=("microwave",),
                timers=(Timer("Cook egg", 60, "Start after the mug is ready"),),
                warnings=("Use a microwave-safe mug.",),
            ),
        ),
        servings=1,
        prep_time_minutes=4,
        cook_time_minutes=1,
        difficulty="easy",
        skill_level="guided_beginner",
        appliances=(ApplianceRequirement("microwave", required=True),),
        allergens=("egg", "dairy"),
        diet_tags=("vegetarian",),
        safety_flags=("heat", "microwave", "adult_help"),
        adult_help_required=True,
        source="curated",
        validation_status="validated",
    ),
    Recipe(
        recipe_id="lunch-hummus-veggie-wrap",
        title="Hummus Veggie Wrap",
        meal_type="lunch",
        summary="A simple wrap with hummus and crunchy vegetables.",
        ingredients=(
            Ingredient("tortilla", amount=1, allergen_tags=("wheat",)),
            Ingredient("hummus", amount="2 tbsp", allergen_tags=("sesame",)),
            Ingredient("carrot sticks", amount="1/4 cup"),
            Ingredient("cucumber slices", amount="1/4 cup"),
        ),
        steps=(
            Step("step-1", 1, "Spread the hummus on the tortilla."),
            Step("step-2", 2, "Add the carrots and cucumber."),
            Step("step-3", 3, "Roll the tortilla into a wrap."),
        ),
        servings=1,
        prep_time_minutes=6,
        cook_time_minutes=0,
        difficulty="easy",
        skill_level="independent_beginner",
        appliances=(),
        allergens=("sesame", "wheat"),
        diet_tags=("vegetarian", "dairy_free"),
        safety_flags=(),
        adult_help_required=False,
        source="curated",
        validation_status="validated",
    ),
    Recipe(
        recipe_id="lunch-air-fryer-pita-pizza",
        title="Air Fryer Pita Pizza",
        meal_type="lunch",
        summary="A warm pita pizza with an adult helping on the hot appliance.",
        ingredients=(
            Ingredient("pita bread", amount=1, allergen_tags=("wheat",)),
            Ingredient("tomato sauce", amount="2 tbsp"),
            Ingredient("mozzarella", amount="1/4 cup", allergen_tags=("dairy",)),
        ),
        steps=(
            Step("step-1", 1, "Spread the sauce on the pita.", safety_level="adult_help", requires_adult_help=True),
            Step(
                "step-2",
                2,
                "Ask an adult to cook the pita in the air fryer for 4 minutes.",
                safety_level="adult_help",
                requires_adult_help=True,
                requires_appliance=("air_fryer",),
                timers=(Timer("Warm pizza", 240, "Start after the pita goes in"),),
                warnings=("The air fryer basket will be hot.",),
            ),
        ),
        servings=1,
        prep_time_minutes=5,
        cook_time_minutes=4,
        difficulty="easy",
        skill_level="guided_beginner",
        appliances=(ApplianceRequirement("air_fryer", required=True),),
        allergens=("wheat", "dairy"),
        diet_tags=("vegetarian",),
        safety_flags=("heat", "air_fryer", "adult_help"),
        adult_help_required=True,
        source="curated",
        validation_status="validated",
    ),
    Recipe(
        recipe_id="dinner-no-cook-chicken-rice-bowl",
        title="No-Cook Chicken Rice Bowl",
        meal_type="dinner",
        summary="A filling dinner bowl that uses ready-to-eat ingredients.",
        ingredients=(
            Ingredient("cooked rice", amount="1 cup"),
            Ingredient("cooked chicken", amount="1 cup"),
            Ingredient("corn", amount="1/4 cup"),
            Ingredient("salsa", amount="2 tbsp"),
        ),
        steps=(
            Step("step-1", 1, "Put the rice in a bowl."),
            Step("step-2", 2, "Add the chicken and corn."),
            Step("step-3", 3, "Spoon salsa on top."),
        ),
        servings=1,
        prep_time_minutes=5,
        cook_time_minutes=0,
        difficulty="easy",
        skill_level="independent_beginner",
        appliances=(),
        allergens=(),
        diet_tags=("dairy_free",),
        safety_flags=(),
        adult_help_required=False,
        source="curated",
        validation_status="validated",
    ),
    Recipe(
        recipe_id="dinner-stove-pasta-marinara",
        title="Stove Pasta Marinara",
        meal_type="dinner",
        summary="A pasta dinner that needs adult help for the hot stove step.",
        ingredients=(
            Ingredient("pasta", amount="2 cups", allergen_tags=("wheat",)),
            Ingredient("marinara sauce", amount="1 cup"),
            Ingredient("parmesan", amount="2 tbsp", allergen_tags=("dairy",)),
        ),
        steps=(
            Step("step-1", 1, "Ask an adult to boil the pasta on the stove.", safety_level="adult_help", requires_adult_help=True, requires_appliance=("stove",)),
            Step(
                "step-2",
                2,
                "Drain the pasta with help from an adult.",
                safety_level="adult_help",
                requires_adult_help=True,
                warnings=("The pot and water will be hot.",),
            ),
            Step("step-3", 3, "Stir in the marinara sauce."),
            Step("step-4", 4, "Sprinkle parmesan on top if you want."),
        ),
        servings=2,
        prep_time_minutes=8,
        cook_time_minutes=12,
        difficulty="medium",
        skill_level="guided_beginner",
        appliances=(ApplianceRequirement("stove", required=True),),
        allergens=("wheat", "dairy"),
        diet_tags=("vegetarian",),
        safety_flags=("heat", "stove", "adult_help"),
        adult_help_required=True,
        source="curated",
        validation_status="validated",
    ),
    Recipe(
        recipe_id="snack-apple-yogurt-dip",
        title="Apple Yogurt Dip",
        meal_type="snack",
        summary="Apple slices with a quick yogurt dip.",
        ingredients=(
            Ingredient("apple", amount=1, preparation="sliced"),
            Ingredient("plain yogurt", amount="1/2 cup", allergen_tags=("dairy",)),
            Ingredient("cinnamon", amount="1/4 tsp"),
        ),
        steps=(
            Step("step-1", 1, "Put the yogurt in a bowl."),
            Step("step-2", 2, "Stir in the cinnamon."),
            Step("step-3", 3, "Dip the apple slices and eat."),
        ),
        servings=1,
        prep_time_minutes=5,
        cook_time_minutes=0,
        difficulty="easy",
        skill_level="independent_beginner",
        appliances=(),
        allergens=("dairy",),
        diet_tags=("vegetarian",),
        safety_flags=(),
        adult_help_required=False,
        source="curated",
        validation_status="validated",
    ),
    Recipe(
        recipe_id="snack-microwave-mug-cake",
        title="Microwave Mug Cake",
        meal_type="snack",
        summary="A warm snack cake that needs adult help for the microwave.",
        ingredients=(
            Ingredient("flour", amount="4 tbsp", allergen_tags=("wheat",)),
            Ingredient("sugar", amount="2 tbsp"),
            Ingredient("egg", amount=1, allergen_tags=("egg",)),
            Ingredient("milk", amount="3 tbsp", allergen_tags=("dairy",)),
        ),
        steps=(
            Step("step-1", 1, "Mix the flour, sugar, egg, and milk in a mug.", safety_level="adult_help", requires_adult_help=True),
            Step(
                "step-2",
                2,
                "Ask an adult to microwave the mug for 45 seconds.",
                safety_level="adult_help",
                requires_adult_help=True,
                requires_appliance=("microwave",),
                timers=(Timer("Bake cake", 45, "Start after the mug is mixed"),),
                warnings=("The mug will be hot.",),
            ),
        ),
        servings=1,
        prep_time_minutes=5,
        cook_time_minutes=1,
        difficulty="easy",
        skill_level="guided_beginner",
        appliances=(ApplianceRequirement("microwave", required=True),),
        allergens=("egg", "dairy", "wheat"),
        diet_tags=("vegetarian",),
        safety_flags=("heat", "microwave", "adult_help"),
        adult_help_required=True,
        source="curated",
        validation_status="validated",
    ),
)
